import asyncio
import uuid

from grpclib.client import Channel
import pytest
from loguru import logger

# generated by protoc
from generated.message import MessageRequest, MessageStub


@pytest.fixture(scope="module")
def host():
    return "127.0.0.1"


@pytest.fixture(scope="module")
def port():
    return 50051


def test_message_stream(host, port):
    async def main(host, port):
        async with Channel(host, port) as channel:
            messager = MessageStub(channel)
            request_id = str(uuid.uuid1())
            count = 2
            logger.debug(f"request:{request_id=},{count=}")
            async for response in messager.stream_message(
                request_id=request_id, count=count
            ):
                logger.debug(f"{response=}")

    asyncio.run(main(host, port))
